FROM centos:7.6.1810

RUN yum install -y python python-devel epel-release
RUN yum install -y python2-pip gcc

COPY data-service/src/main/resources /data-service/

WORKDIR /data-service

RUN pip install -r requirements.txt
