FROM python:3.6-alpine as wheels-builder

RUN apk add --no-cache build-base
RUN pip3 install --upgrade pip
RUN pip3 wheel thriftpy2==0.4.8



FROM python:3.6-alpine

#RUN apk add --no-cache build-base

COPY data-service/src/main/resources /data-service/

COPY --from=wheels-builder \
    /thriftpy2-0.4.8-cp36-cp36m-linux_x86_64.whl \
    /

WORKDIR /data-service

RUN pip3 install /thriftpy2-0.4.8-cp36-cp36m-linux_x86_64.whl && \
    pip3 install -r requirements.txt

